#!/usr/bin/env python3
"""Generate docs/reference/cli.md from da-cli's argparse tree.

Run via ``make docs``. CI regenerates and fails on a diff, so the
reference cannot drift from the code — the failure mode that left
AGENTS.md missing four subcommands and every global flag.

Dev-time only: nothing here is imported at runtime, so ADR-0001's
stdlib-only, zero-runtime-dependency rule is unaffected.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

import dacli  # noqa: E402  (needs the sys.path line above)

OUTPUT = REPO_ROOT / "docs" / "reference" / "cli.md"

BANNER = (
    "<!-- Auto-generated by tools/gen_cli_docs.py — do not edit.\n"
    "     Regenerate with `make docs`. CI fails if this file is stale. -->"
)

# Hand-written context for each top-level command group. Generated help
# text says what a flag does; these say when you would want it. Keeping
# the prose here rather than in the markdown means it survives
# regeneration.
GROUP_NOTES: dict[str, str] = {
    "auth": (
        "One-time browser login. `da auth` opens DeviantArt, captures the "
        "callback on a local HTTPS listener, and writes tokens to "
        "`state.json`. Re-run it only if you revoke the app or the "
        "refresh token expires (90 days)."
    ),
    "sync": (
        "The three sync modes differ in *what they walk*, not in how they "
        "save:\n\n"
        "- `sync feed` — new items from your watch feed. Incremental and "
        "cheap; this is the one to schedule.\n"
        "- `sync artist` — one artist's whole gallery, newest first, "
        "stopping at the first item already on disk.\n"
        "- `sync watched` — every artist you watch, one gallery at a time. "
        "Slow; use for the initial backfill.\n\n"
        "All three are resumable, skip what is already downloaded, and "
        "write atomically."
    ),
    "search": (
        "Read-only browse commands. `topic` and `tag` are different things "
        "on DeviantArt: a *topic* is one of DA's curated editorial "
        "categories (list them with `da search topics`), while a *tag* is "
        "free-text applied by the artist."
    ),
    "config": "Read and write settings. Secrets are masked in all output.",
    "index": (
        "The SQLite index at `~/.local/state/da-cli/index.db` records what "
        "has already been downloaded, so a repeat sync costs one API call "
        "instead of a full re-walk. It self-heals; `index rebuild` is only "
        "needed if you move or restore the destination folder."
    ),
    "deviation": "Metadata for a single deviation, by id.",
    "user": "Public profile information for one DeviantArt user.",
    "watch": "List the artists your account watches.",
    "daily": "DeviantArt's editorially chosen Daily Deviations for a date.",
    "whoami": "Verify the stored token and show which account it belongs to.",
    "refresh": "Force an access-token refresh without waiting for expiry.",
    "diagnose": (
        "End-to-end health check: config, credentials, token liveness, "
        "destination writability, index integrity, and the scheduled job. "
        "Exits 0 when everything passes, 1 on warnings, 2 on failures — "
        "suitable for a monitored cron job. `--json` emits the same "
        "findings machine-readably."
    ),
    "bench": (
        "Synthetic sync against a mocked HTTP layer. Measures CLI overhead "
        "only — no network, no DeviantArt account needed."
    ),
}


def _formatter(prog: str) -> argparse.HelpFormatter:
    """Fixed-width formatter.

    argparse defaults to the terminal width via ``COLUMNS``, which would
    make the generated file differ per machine and turn the CI diff
    check into noise. Pin it.
    """
    return argparse.HelpFormatter(prog, max_help_position=30, width=78)


def _format_help(parser: argparse.ArgumentParser) -> str:
    parser.formatter_class = _formatter
    return parser.format_help().rstrip()


def _subparsers(parser: argparse.ArgumentParser) -> dict[str, argparse.ArgumentParser]:
    """Return this parser's subcommands, or {} if it has none.

    argparse exposes no public API for walking a subparser tree, so the
    private attributes below are the only way. They have been stable
    since Python 3.2 and the generator is dev-only — a break shows up
    as a failed `make docs`, never as a runtime error for a user.
    """
    for action in parser._actions:  # noqa: SLF001
        if isinstance(action, argparse._SubParsersAction):  # noqa: SLF001
            return dict(action.choices)
    return {}


def _walk(parser: argparse.ArgumentParser, path: str, depth: int, out: list[str]) -> None:
    children = _subparsers(parser)
    heading = "#" * min(depth, 6)
    out.append(f"{heading} `{path}`")
    out.append("")

    note = GROUP_NOTES.get(path.split(" ", 1)[1] if " " in path else "")
    if note and depth == 2:
        out.append(note)
        out.append("")

    if parser.description and not children:
        out.append(parser.description.strip())
        out.append("")

    out.append("```text")
    out.append(_format_help(parser))
    out.append("```")
    out.append("")

    for name, child in children.items():
        _walk(child, f"{path} {name}", depth + 1, out)


def build() -> str:
    parser = dacli.build_parser()
    out: list[str] = [
        BANNER,
        "",
        "# Command reference",
        "",
        f"Every `da` command and flag, generated from `build_parser()` in "
        f"the `dacli` package (version {dacli.__version__}).",
        "",
        "For settings that live in a config file rather than on the command "
        "line, see [configuration](configuration.md). For what each exit code "
        "means, see [exit codes](exit-codes.md).",
        "",
    ]
    _walk(parser, "da", 2, out)
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    text = build()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    previous = OUTPUT.read_text() if OUTPUT.exists() else None
    OUTPUT.write_text(text)
    if previous == text:
        print(f"{OUTPUT.relative_to(REPO_ROOT)} is up to date")
    else:
        print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
